SyntaxError: invalid syntax (<ipython-input-3-d4d2da6efe03>, line 1)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.model_selection import train_test_split
import random
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.metrics import mean_absolute_error
import xport as xport

In [6]:
df = pd.read_sas('LDL_Trigy.XPT')
df

,SEQN,WTSAF2YR,LBXTR,LBDTRSI,LBDLDL,LBDLDLSI,LBDLDLM,LBDLDMSI,LBDLDLN,LBDLDNSI
0,93708.0,2.565368e+04,58.0,0.655,109.0,2.819,107.0,2.767,111.0,2.870
1,93711.0,2.922605e+04,48.0,0.542,156.0,4.034,152.0,3.931,158.0,4.086
2,93717.0,1.371510e+05,102.0,1.152,140.0,3.620,138.0,3.569,142.0,3.672
3,93718.0,5.888331e+04,46.0,0.519,80.0,2.069,77.0,1.991,79.0,2.043
4,93719.0,5.397605e-79,80.0,0.903,35.0,0.905,35.0,0.905,35.0,0.905
...,...,...,...,...,...,...,...,...,...,...
3031,102947.0,3.208847e+04,35.0,0.395,66.0,1.707,62.0,1.603,64.0,1.655
3032,102948.0,2.911334e+05,52.0,0.587,123.0,3.181,119.0,3.077,124.0,3.207
3033,102952.0,3.273305e+04,78.0,0.881,43.0,1.112,43.0,1.112,43.0,1.112
3034,102954.0,5.063745e+04,49.0,0.553,108.0,2.793,104.0,2.689,108.0,2.793
3035,102956.0,9.233024e+04,269.0,3.037,75.0,1.940,94.0,2.431,84.0,2.172